name: reader
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  auto_route: ^7.8.3
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  epub_view: ^3.2.0
  flutter:
    sdk: flutter
  flutter_icons:
    git: https://github.com/jibiel/flutter-icons
  flutter_riverpod: ^2.4.0
  flutter_spinkit: ^5.2.0
  freezed_annotation: ^2.4.1
  google_fonts: ^6.0.0
  json_annotation: ^4.8.1
  logger: ^2.0.2
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.3.0
  riverpod_annotation: ^2.1.5
  sembast: ^3.5.0+1
  share_plus: ^7.1.0
  shared_preferences: ^2.2.1
  xml2json: ^6.2.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  custom_lint: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/
